### PR TITLE
Added show method for genambig, Genotypes

### PR DESCRIPTION
**Pull request by plantarum**
Hi Dr. Clark,

Thanks for sharing polysat, it's great! I hope it's not too forward, I've made a few suggestions to enhance interactive viewing of genambig objects at the command prompt. I'm happy to make changes to this, or you can ignore it completely, as you like. 

The original version of Genotypes produced an awkwardly formatted matrix,
with heterozygous loci reported as 'integer(3)'. I modified the method so
that it actually shows a character representation of the genotype (e.g., "240/246/252"). It would be easy to modify this to just show the number of alleles (i.e., '3'), or any other useful summary of the genotype.

Here's what the output looks like with my change:

```
> Genotypes(simgen)
     loc1              loc2              loc3             
A1   "110/112/106"     "164/155/161"     "218/214/216/222"
A2   "114/106/118/110" "158/161"         "222/218/230"    
A3   "114/102/100/106" "158/161/155/152" "230/210/218"    
A4   "110/102/106/100" "161/155/158"     "214/218/216/230"
A5   "106/112"         "155/152"         "214/218"        
```

I also added a `show` method for class genambig. This adds a bit of
formatting to the display to make it a little easier to parse when viewed
at the console.

Here's the output, with the Genotypes matrix truncated for space:

```
> simgen
Insert dataset description here. 
Missing values:  -9 

Genotypes: 
     loc1              loc2              loc3             
A1   "110/112/106"     "164/155/161"     "218/214/216/222"
A2   "114/106/118/110" "158/161"         "222/218/230"    
A3   "114/102/100/106" "158/161/155/152" "230/210/218"    
A4   "110/102/106/100" "161/155/158"     "214/218/216/230"
A5   "106/112"         "155/152"         "214/218"        
...    ...                      ...                     ...
C98  "116/112"         "143/155"         "226/220"        
C99  "114/116/104"     "146/155/152"     "220/210/212"    
C100 "108/116/104/100" "149/164/155/146" "226/222/210"    

SSR motif lengths: 
 none

Ploidies: 
 none

PopNames: 
 none

PopInfo: 
 none
```

Neither of these changes alters the data at all, just the display when working interactively at the command prompt. We're just starting to use polysat in our lab, so this may break something I'm not aware of.

### CODE REVIEW

**Comment by lvclark** [comment]
No problem, I am happy to have input!  (It might be awhile until the next CRAN submission though barring any major bug discoveries, since I am not currently developing any new features.)

The `Genotypes` method is designed for programmatically accessing the genotypes, not for viewing them.  So your change to that method is very likely to cause problems elsewhere in polysat.  Have you looked at the `viewGenotypes` function to see if it will meet your needs?

Also, have you looked at the `summary` method for printing basic information about a `genambig` object?  I'm not opposed to the creation of a `print` or `show` method in addition to that; it just shouldn't be too redundant.

**Comment by plantarum** [comment]
I see. I left the Genotypes ReplaceMethod alone, so code using the `Genotypes(object) <- something` form should still work. But anything that works the other way would be broken (i.e., `something <- Genotypes(object)`).

`viewGenotypes(object)` does provide the same info. The format I suggested is a bit more compact, so may be a bit more convenient in some cases, but it's not qualitatively different.

The primary issue I see is that my first instinct when looking at an object is to enter its name at the prompt and scan the output. The output polysat produces is copious, but it could be more useful. My first thought was to tinker with the `Genotypes` function, but I could accomplish the same thing without doing that.

If I drop the changes to Genotypes, and instead put that code in the show method for Genambig, the result would be:
- no change to any functions that we count on
- the output of Genambig objects is improved by:
  - showing meaningful Genotypes
  - not filling the screen with long lists of NA when slots are empty
- these changes only effect interactive use, and won't impact anything else in the code

This would compliment `summary(genambig)`, which provides a nice concise summary of the object, without listing all the data.

If you don't like the idea, I'll leave it at that. This just caught my interest and I thought I'd start poking around!

**Comment by lvclark** [comment]
Looks good!  You are not the first person to be surprised and confused at the result of printing out a `genambig` object, and honestly it is probably best for a user to write the `show` method because I am a bit "too close" to the package and perhaps out of touch with what a typical user would want to see.  A few comments:

When the genotypes print out, I would prefer not to see them surrounded by quotation marks, because I don't want to mislead the user into thinking that the genotypes are stored as character strings in the object.  Probably with `cat` there is a way to get it to look nice.

Delete `def <- ` in line 1089 to be consistent with package style.

Also to be consistent with package style, put curly braces after the `if` and `else` statements.  Honestly I am surprised that the function works as-is, because if I construct an if-else statement the way you did outside of a function definition I get an error.  Please do it like this:

```
if(condition){
  command1
} else {
  command2
}
```

Update the `alias` and Methods sections of this file to list your new method: https://github.com/lvclark/polysat/blob/master/man/genambig-class.Rd

Add `show` to the `exportMethods` call in the NAMESPACE file.

Add yourself as a contributor in the DESCRIPTION file :)

If you have the tools on your computer already, please run `R CMD check` on the package to make sure everything is still working.

**Comment by plantarum** [comment]
Done! I ran the R CMD build and R CMD check with R 3.5. There was a warning about having the vignettes present in inst/doc, but nothing else. 

I used print(..., quotes = FALSE) to get rid of the quotes in the output. `cat` was getting pretty hairy, and it would have been tricky to rebuild the columns properly. 

Also, I added a `sort` to put the alleles in order - now they will always appear smallest to highest (i.e., 100/104/114) instead of in arbitrary order (114/100/104).

**Comment by lvclark** [comment]
Great, thanks!

**Pull request merged**
